

class TimeConstants:
    DEGRADATION_CHECK_INTERVAL = 300
    DEGRADATION_MIN_CHECKS = 50
    
    STATS_LOG_INTERVAL = 60
    MEMORY_CLEANUP_INTERVAL = 60
    
    GIFT_CHECK_TIMEOUT = 10.0
    
    HUNTER_INITIAL_DELAY_MAX = 2.0
    PURCHASE_DELAY = 0.5
    QUEUE_PROCESS_DELAY = 0.5
    POST_ERROR_DELAY = 5.0
    
    CHECK_DURATION_FAST = 0.5
    CHECK_DURATION_SLOW = 3.0
    INTERVAL_DECREASE_FACTOR = 0.9
    INTERVAL_INCREASE_FACTOR = 1.1
    INTERVAL_RECOVERY_FACTOR = 0.8
    FLOOD_WAIT_FACTOR = 1.5
    ERROR_INTERVAL_FACTOR = 2.0


class Limits:
    MAX_PROCESSED_GIFTS = 1000
    GC_COLLECTION_INTERVAL = 50
    MIN_INTERVAL_DELAY = 0.1
    CONSECUTIVE_SUCCESS_THRESHOLD = 5
    CONSECUTIVE_ERROR_THRESHOLD = 3
    MAX_UPDATE_QUANTITY = 9999


class FileConstants:
    SESSIONS_DIR = "sessions"
    LOGS_DIR = "logs"
    CREDENTIALS_FILE = ".credentials.json"
    LOG_FILE_PATTERN = "gift_sniper_{time:YYYY-MM-DD}.log"
    LOG_RETENTION_DAYS = 7
    CREDENTIALS_FILE_PERMISSIONS = 0o600


class TelegramConstants:
    API_HASH_LENGTH = 32
    
    ERROR_INSUFFICIENT_BALANCE = "STARS_BALANCE_INSUFFICIENT"
    ERROR_GIFT_SOLD_OUT = "GIFT_SOLD_OUT"


class AppInfo:
    NAME = "Telegram Gift Sniper"
    VERSION = "2.0.0"